version: "3.7"
services:
  backend:
    build:
      context: backend
    ports:
      - 4000:4000
    volumes:
      - backend:/backend/src

  frontend:
    build:
      context: frontend
    ports:
      - 3000:3000
    volumes:
      - frontend:/frontend/src
      - /project/node_modules
    expose:
      - 3306
      - 33060
      - 4000
volumes:
  frontend: {}
    