version: "3.7"
services:
  frontend:
    container_name: 'chicago_business_intelligence_ui'
    environment:
      PORT: 4000
      CHOKIDAR_USEPOLLING: 'true'
    build:
      context: './chicago_business_intelligence'
      dockerfile: Dockerfile
    ports: 
      - '4000:4000'
    