version: "3.7"
services:
  frontend:
    build:
      context: frontend
      target: development
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/code/src
      - /project/node_modules
    depends_on:
      - backend
    expose:
      - 3306
      - 33060
      - 4000
    