apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservices
  labels:
    app: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservices
  template:
    metadata:
      labels:
        app: microservices
    spec:
      containers:
      - name: app
        image: rahulbhatra/microservices:latest
        env:
          - name: PING_URLS
            value: https://google.com