--------------------------------- ALL CREATE STATEMENTS ---------------------------------
/*
Taxi Trip Data:
https://data.cityofchicago.org/Transportation/Taxi-Trips/wrvz-psew
https://data.cityofchicago.org/Transportation/Transportation-Network-Providers-Trips/m6dm-c72p/data
*/
CREATE TABLE TAXI_TRIPS_DATA
(
TRIP_ID VARCHAR(50) PRIMARY KEY,
TRIP_START_TIME TIMESTAMP NOT NULL,
TRIP_END_TIME TIMESTAMP NOT NULL,
PICKUP_LAT NUMBER NOT NULL,
PICKUP_LONG NUMBER NOT NULL,
DROPOFF_LAT NUMBER NOT NULL,
DROPOFF_LONG NUMBER NOT NULL,
PICKUP_ZIP NUMBER NOT NULL,
DROPOFF_ZIP NUMBER NOT NULL,
SYS_CREATION_DATE TIMESTAMP NOT NULL,
SYS_UPDATE_DATE TIMESTAMP NOT NULL
);

/*
Covid CCVI Data:
https://data.cityofchicago.org/Health-Human-Services/Chicago-COVID-19-Community-Vulnerability-Index-CCV/xhc6-88s9/data
*/
CREATE TABLE COVID_CCVI_DATA
(
GEOGRAPHY_TYPE VARCHAR(10) NOT NULL,
ZIP_CODE NUMBER NOT NULL,
CCVI_SCORE NUMBER NOT NULL,
CCVI_CATEGORY VARCHAR(10) NOT NULL,
SYS_CREATION_DATE TIMESTAMP NOT NULL,
SYS_UPDATE_DATE TIMESTAMP NOT NULL,
PRIMARY KEY (GEOGRAPHY_TYPE, ZIP_CODE)
);

/*
Covid Weekly Data:
https://www.chicago.gov/city/en/depts/bldgs/dataset/building_permits.html
*/
CREATE TABLE COVID_WEEKLY_DATA
(
ZIP_CODE NUMBER NOT NULL,
WEEK_NUMBER NUMBER NOT NULL,
WEEK_START_DATE DATE NOT NULL,
WEEK_END_DATE DATE NOT NULL,
CASES_PER_WEEK NUMBER NOT NULL,
CASES_CUMULATIVE NUMBER NOT NULL,
PERCENT_POSITIVE NUMBER NOT NULL,
PERCENT_POSITIVE_ACCUM NUMBER NOT NULL,
SYS_CREATION_DATE TIMESTAMP NOT NULL,
SYS_UPDATE_DATE TIMESTAMP NOT NULL,
PRIMARY KEY (ZIP_CODE, WEEK_NUMBER)
);

/*
Covid Daily Data:
https://data.cityofchicago.org/Health-Human-Services/COVID-19-Daily-Cases-Deaths-and-Hospitalizations/naz8-j4nc/data
*/
CREATE TABLE COVID_DAILY_DATA
(
DAY_DATE DATE PRIMARY KEY,
TOTAL_CASE NUMBER NOT NULL,
TOTAL_DEATHS NUMBER NOT NULL,
SYS_CREATION_DATE TIMESTAMP NOT NULL,
SYS_UPDATE_DATE TIMESTAMP NOT NULL
);

/*
Unemployment and Poverty Data
https://data.cityofchicago.org/Health-Human-Services/Unemployment/ymyn-s5a8
*/
CREATE TABLE UNEMPLOYMENT_POVERTY_DATA
(
ZIP_CODE NUMBER NOT NULL,
AREA_CODE NUMBER NOT NULL,
AREA_NAME VARCHAR(50),
PERCENT_HOUSING_OCCUPIED NUMBER NOT NULL,
PERCENT_BELOW_POVERTY NUMBER NOT NULL,
PERCENT_UNEMPLOYED NUMBER NOT NULL,
SYS_CREATION_DATE TIMESTAMP NOT NULL,
SYS_UPDATE_DATE TIMESTAMP NOT NULL,
PRIMARY KEY (ZIP_CODE, AREA_CODE)
);
